### DISCUSSION TITLE
Searchstring Wortkombination mit Leerzeichen

### DISCUSSION THREAD

**Discussion by ChristianRoze80** [geimist/synOCR#53] [Q&A] [answered]
Hallo Meine Regel gilt leider immer als nicht erfüllt:
Die Quelle ist eine Rechnung eines Lieferanten. Hierzu muss ich z.B. nach der Wortkombination "Klaus Mustermann" suchen. Das Problem ist offenbar das Leerzeichen zwischen den Wörtern.

Meinen Searchstring habe ich so gestaltet:
rule_010:
    tagname: §tagname_RegEx
    tagname_RegEx: (?i)(Klaus Mustermann)
    condition: all
    subrules:
    - searchstring: (?i)(Klaus Mustermann)
      searchtyp: contains
      isRegEx: true

**Comment by geimist** [comment]
Eigentlich sollte das so gehen (sofern dein YAML nicht so unkorrekt formatiert ist, wie in der Frage).

Aber du kommst doch wesentlich einfacher an dein Ziel:
```YAML
rule_010:
    tagname: Klaus Mustermann
    condition: all
    subrules:
    - searchstring: Klaus Mustermann
      searchtyp: contains
      casesensitive: false
```
Achte in YAML unbedingt auf die korrekte Anzahl der führenden Leerzeichen!

**Reply by ChristianRoze80** [reply]
Offenbar hat mein Problem mit dem vewendeten Suchstring zu tun.
So sieht meine Original Regel aus, die nicht "satisfied" wird:
```yaml
rule_1000:
    tagname: Bauzentrum_Hofacker_
    condition: all
    subrules:
    - searchstring: "Bauzentrum Hofacker"
```
Die durch OCR erkannten Daten sehen so aus:
``
Bauzentrum Hofacker * Wiesenbornstraße 72 * 63571 Gelnhausen
``
So funktioniert die Regel:
```yaml
rule_1000:
    tagname: Bauzentrum_Hofacker_
    condition: all
    subrules:
    - searchstring: "Bauzentrum"
    - searchstring: "Hofacker"
```
