### DISCUSSION TITLE
Mehrer YAML Dateien für "zu suchende Tags"

### DISCUSSION THREAD

**Discussion by Sunris89** [geimist/synOCR#62] [Q&A] [answered]
Hallo,
Ich versuche aktuell mehrere YAML Dateien für die Tag-suche zu verwenden. 
Mein Eintrag in der GUI sieht wie folgt aus:
```
/volume1/scan_import/YAML/synOCR_YAML_default.txt;/volume1/scan_import/YAML/synOCR_YAML_rechnungen.txt
``` 
der log gibt folgendes aus:
```
  ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
  ● STEP 2 - SEARCH TAGS / RENAME / SORT:                                           ●
  ●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●


●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
CURRENT FILE:   ➜ 2135175.pdf

  -----------------------------------------------------------------------------------
  | search tags in ocr text:                                                        |
  -----------------------------------------------------------------------------------

                source for tags is the list from the GUI
                tag count:       2
                  Search by tag:   "/volume1/scan_import/YAML/synOCR_YAML_default.txt" ➜  -
                  Search by tag:   "/volume1/scan_import/YAML/synOCR_YAML_rechnungen.txt" ➜  -

                rename tag is: ""


``` 
Inhalt aus "/volume1/scan_import/YAML/synOCR_YAML_rechnungen.txt"
```
# synOCR_YAMLRULEFILE   # keep this line!


rule_1001:
#X#X#: Rechnungen
    tagname: §tagname_RegEx
    targetfolder: /volume1/scan_import/OCR
    tagname_RegEx: (?i)(Rechnung|Invoice|Lieferschein|delivery note|Quittung|receipt|Bestellung|Auftrag|Online-Bestellung|Online-Auftrag|order|Barkauf|Barverkauf|cash purchase|Kundenbeleg)
    postscript: mv "${output}" "${output%/*}/$(echo "${output##*/}" | sed 's/ /_/g')"
    condition: all
    subrules:
    - searchstring: (?i)(Rechnung|Invoice|Lieferschein|delivery note|Quittung|receipt|Bestellung|Auftrag|Online-Bestellung|Online-Auftrag|order|Barkauf|Barverkauf|cash purchase|Kundenbeleg)
      searchtyp: contains
      isRegEx: true
``` 
Einzeln funktionieren die YAML-Files einwandfrei.

Gruß Andreas
