### DISCUSSION TITLE
Person als eigene Variable (zur Dateiverschiebung sowie Umbenennung)

### DISCUSSION THREAD

**Discussion by erd82** [geimist/synOCR#8] [Ideas]
Hallo Stephan,

Ich bin mir nicht sicher, ob dieser Use Case bereits abgedeckt bzw. unterstützt ist.

Nehmen wir an, wir wollen Dokumente **verschiedener Personen** verarbeiten und diese personenbezogen in unserer Ordnerstruktur ablegen. Jede Person hat einen eigenen root-Folder (`/volume1/data/<person>/`), in dem es jeweils die gleichen Hauptordner gibt (wie Gesundheit, Versicherungen, Finanzen, Steuer, Rechnungen, etc.).

Wie könnte dies umgesetzt werden?
- Personen werden in der YAML-Datei nicht als Tags, sondern als eigene Variable (z.B. `§person`) behandelt.
- In der YAML-Datei müssten alle möglichen Personen vordefiniert werden (um den Kreis der betrachteten Personen einzuschränken), z.B.
```
persons:
- name: Max Mustermann
  condition: any
  subrules:
  - searchstring: <RegEx-string>
    searchtyp: is
    isRegEx: true
  - searchstring: Mustermann, Max
  - searchstring: Max Mustermann
- name: Erika Mustermann
  condition: any
  subrules:
  - searchstring: <RegEx-string>
    searchtyp: is
    isRegEx: true
  - searchstring: Mustermann, Erika 
  - searchstring: Erika Mustermann
```
- Wenn eine der Personen im verarbeiteten Dokument gefunden wurde (z.B. als Adressat, Patient, etc.), wird diese als Variable `§person` festgelegt.
- Die Variable `§person` kann nun wie folgt verwendet werden:
  1. in den Regeln der YAML-Datei selbst (z.B. im Target Folder targetfolder: `/volume1/data/§person/Gesundheit/`) oder 
  2. bei der Umbenennung der Datei (z.B. `§yocr4-§mocr-§docr -§person §tag`)

Vielleicht denke ich zu kompliziert und man kann dies schon auf andere Weise viel einfacher realisieren. Aber vielleicht ist das auch eine Idee für eine zukünftige Umsetzung. :-)

Entschuldigt, wenn ich gerade so viele Anfragen / Überlegungen poste. Aber das Projekt hat mich wirklich sehr positiv beeindruckt!

Viele Grüße, erd
