### ISSUE TITLE
Tag-Steuerung beim Zutreffen mehrerer Regeln

### ISSUE THREAD

**Issue by cartman0208** [geimist/synOCR#54]
Heidiho,

Erstmal danke für das Tool, macht mein Leben deutlich einfacher, mir fällt da nur ein Problem auf.
Evtl. habe ich das in der Doku überlesen, aber: gibt es eine Möglichkeit den korrekten Tag zu setzen, wenn mehrere Regeln zutreffen?
Beispiel: 
Ich bekomme eine Congstar Rechnung, dort steht weiter unten aber "Telekom" drin (für deren Rechnungen ich eine separate Regel habe)
`Congstar:
    tagname: Congstar§tagname_RegEx
    tagname_RegEx: ((?:Jan(?:uar)?|Feb(?:ruar)?|Mär(?:z)?|Apr(?:il)?|Mai$|Jun(?:i)?|Jul(?:i)?|Aug(?:ust)?|Sep(?:tember)?|Sept|Okt(?:ober)?|Nov(?:ember)?|Dez(?:ember)?))
    condition: any
    subrules:
    - searchstring: congstar
      searchtyp: contains
      isRegEx: false
      source: content
      casesensitive: true
`
`Telekom:
    tagname: Telekom§tagname_RegEx
    tagname_RegEx: ((?:Jan(?:uar)?|Feb(?:ruar)?|Mär(?:z)?|Apr(?:il)?|Mai$|Jun(?:i)?|Jul(?:i)?|Aug(?:ust)?|Sep(?:tember)?|Sept|Okt(?:ober)?|Nov(?:ember)?|Dez(?:ember)?))
    condition: all
    subrules:
    - searchstring: Telekom Deutschland
      searchtyp: contains
      isRegEx: false
      source: content
      casesensitive: false
`
Als Ergebnis wäre der Tag "CongstarFebruarTelekomFebruar"

Analog habe ich eine Regel für "Rechnung" und eine für "Mahnung" ... taucht beides im Dokument auf, wird auch beides als Tag gesetzt
Gibts dafür eine elegante Lösung?
Danke für die Mühe

**Comment by geimist** [comment]
Bitte sei so freundlich und [formatiere YAML-Code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) gut lesbar.

Das geht so:
````
```YAML
regel:
    - result: schön lesbar
      und strukturiert
```
````
Vielen Dank.

**Comment by cartman0208** [comment]
Scheinbar war das mit den Github Codetags ein Fehler... Ohne geht's besser

**Comment by geimist** [comment]
Danke, so ist es besser 👌

Derzeit gibt es keine Möglichkeit, Bedingungen zwischen Regeln zu definieren. Aber helfen dir nicht differenzierte Unterregeln, wie z.B. in dieser Art:
```
rule_01:
    tagname: Telekom§tagname_RegEx
    tagname_RegEx: ((?:Jan(?:uar)?|Feb(?:ruar)?|Mär(?:z)?|Apr(?:il)?|Mai$|Jun(?:i)?|Jul(?:i)?|Aug(?:ust)?|Sep(?:tember)?|Sept|Okt(?:ober)?|Nov(?:ember)?|Dez(?:ember)?))
    condition: all
    subrules:
    - searchstring: Telekom Deutschland
      searchtyp: contains
      isRegEx: false
      source: content
      casesensitive: false
    - searchstring: congstar
      searchtyp: does not contain
```
Hier wird der Tag `Telekom` nur gesetzt, wenn `congstar` nicht vorkommt.

Möglicherweise hilft dir auch eine `subrule:` mit angepasstem `source: filename`, falls der Dateiname eindeutige Informationen liefert.
