### ISSUE TITLE
File naming: avoid double space or underscore when no tag available

### ISSUE THREAD

**Issue by Merinorus** [geimist/synOCR#58]
Hello,

First of all, I'm sorry if the issue has already been addressed, I don't speak German.

Let's say we choose to name our files like this: `§y-§m-§d §tag §tit`, or `§y-§m-§d_§tag_§tit`.

When no tag is found, the `§tag` part is deleted, but the file will have double space or double underscore like this: `2025-02-06  example.pdf` or `2025-02-06__example.pdf`.

Is there a way to make a workaround for this one? I think only the tag might not exist, all other variables always exist.

I imagined something such as: if the `§tag` is surrounded by the same char before and after, and there is no tag, then remove one of the surrounding chars.

Thank you for this great piece of software!

**Comment by geimist** [comment]
Hello,
Yes, you're right. I've noticed that too and I just haven't corrected it yet – I'm sorry.
I'll put it on the to-do list.

Until then, you can help yourself with a `postscript` if you also use a YAML rule file. Just add the following wildcard rule. 
Restriction: The `postscript` only sees the last memory path in the variable `$output`. So if several rules with different paths apply, only the name of the last file is corrected.

```YAML
rule_wildcard:
    tagname:
    postscript: mv -- "${output}" "${output%/*}/$(tr -s ' ' <<<"${output##*/}")"
    condition: any
    subrules:
    - searchstring: .
      searchtyp: contains
      isRegEx: true
```

I hope this helps you.

Best regards 
Stephan
